# coding: utf-8

PERCUSSION_SHORTHANDS = {
    "k": (35, "Acoustic Bass Drum"),
    "K": (36, "Electric Bass Drum"),
    "ss": (37, "Side Stick"),
    "s": (38, "Acoustic Snare"),
    "hc": (39, "Hand Clap"),
    "S": (40, "Electric Snare"),
    "t0": (41, "Low Floor Tom"),
    "h": (42, "Closed Hi-hat"),
    "t1": (43, "High Floor Tom"),
    "H": (44, "Pedal Hi-hat"),
    "t2": (45, "Low Tom"),
    "o": (46, "Open Hi-hat"),
    "t3": (47, "Low-Mid Tom"),
    "t4": (48, "Hi-Mid Tom"),
    "c": (49, "Crash Cymbal 1"),
    "t5": (50, "High Tom"),
    "r": (51, "Ride Cymbal 1"),
    "cc": (52, "Chinese Cymbal"),
    "rb": (53, "Ride Bell"),
    "tr": (54, "Tambourine"),
    "sc": (55, "Splash Cymbal"),
    "cb": (56, "Cowbell"),
    "C": (57, "Crash Cymbal 2"),
    "v": (58, "Vibraslap"),
    "R": (59, "Ride Cymbal 2"),
    "b1": (60, "High Bongo"),
    "b0": (61, "Low Bongo"),
    "m1": (62, "Mute High Conga"),
    "c1": (63, "Open High Conga"),
    "c0": (64, "Low Conga"),
    "T1": (65, "High Timbale"),
    "T0": (66, "Low Timbale"),
    "a1": (67, "High Agogô"),
    "a0": (68, "Low Agogô"),
    "ca": (69, "Cabasa"),
    "m": (70, "Maracas"),
    "sw": (71, "Short Whistle"),
    "lw": (72, "Long Whistle"),
    "sg": (73, "Short Guiro"),
    "lg": (74, "Long Guiro"),
    "cs": (75, "Claves"),
    "w1": (76, "High Woodblock"),
    "w0": (77, "Low Woodblock"),
    "mc": (78, "Mute Cuica"),
    "oc": (79, "Open Cuica"),
    "mt": (80, "Mute Triangle"),
    "ot": (81, "Open Triangle"),
}
